CREATE TABLE `article` (
	boardNo INT PRIMARY KEY AUTO_INCREMENT,
	`group` VARCHAR(20) NOT NULL,
	`cate` VARCHAR(20) NOT NULL,
	title VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	writer VARCHAR(20) NOT NULL,
	`date` DATETIME NOT NULL,
	regip  VARCHAR(100),
	`file` int DEFAULT 0,
	`hit` INT DEFAULT 0,
	comNo int DEFAULT 0	

);